export PATH="/usr/local/bin:/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/Users/msch/Library/Python/2.7/bin:$PATH"
export PATH="/Users/msch/gosrc/bin:/Users/msch/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"


export GOPATH=$HOME/gosrc
export GOBIN=$GOPATH/bin

source ~/src/antigen/antigen.zsh
antigen use oh-my-zsh

antigen bundle git
antigen bundle pyenv

# syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme mh

# Tell antigen that you're done. 
antigen apply


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#powerline-config tmux setup
export DISABLE_AUTO_TITLE='true'
export EDITOR='nvim'
alias ckan='mono ~/bin/ckan.exe'
alias vizsh='nvim ~/.zshrc'
alias szs='source ~/.zshrc'
alias ppt='papertrail'

bindkey '[D' beginning-of-line
bindkey '[C' end-of-line

# ZSH Hooks
function precmd {
  # vcs_info
  # Put the string "hostname::/full/directory/path" in the title bar:
  #echo -ne "\e]2;$PWD\a"
  # Put the parentdir/currentdir in the tab
  echo -ne "\e]1;$PWD:h:t/$PWD:t\a"
}

# There is propably a better way
source /Users/msch/src/dotfiles/dot/zsh/tmux_functions.zsh

fpath=(/usr/local/share/zsh-completions $fpath)


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Setup cdg function shell bookmarks with fzf
# https://dmitryfrank.com/articles/shell_shortcuts
# ------------------
unalias cdg 2> /dev/null
cdg() {
   local dest_dir=$(cdscuts_glob_echo | fzf )
   if [[ $dest_dir != '' ]]; then
      cd "$dest_dir"
   fi
}
export -f cdg > /dev/null

cdg-add () {
    local curr_dir="${PWD} # $*"
    if ! grep -Fxq "$curr_dir" ~/.cdg_paths; then
        echo "$curr_dir" >> ~/.cdg_paths
    fi
}

eval "$(pyenv init -)"
                
export HOMEBREW_GITHUB_API_TOKEN="450bc6672beb266581a2e6c1036db345c6dc2241"



# export PATH="/usr/local/opt/ruby@2.3/bin:$PATH"
